services:
  - type: web
    name: attendify-face-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: MONGODB_URL
        sync: false
